"""Python interface to the C5.0 GPL core."""

from ._c50 import (
    C50Error,
    ConditionKind,
    ContinuousThreshold,
    Model,
    ModelInspection,
    ModelKind,
    NodeKind,
    Options,
    Predictions,
    Predictor,
    RuleInspection,
    RulesetInspection,
    SplitCondition,
    TreeBranch,
    TreeInspection,
    TreeNode,
    load,
    train,
    train_dense,
)
from .inspection import export_json, export_text

__all__ = [
    "C50Error",
    "ConditionKind",
    "ContinuousThreshold",
    "Model",
    "ModelInspection",
    "ModelKind",
    "NodeKind",
    "Options",
    "Predictions",
    "Predictor",
    "RuleInspection",
    "RulesetInspection",
    "SplitCondition",
    "TreeBranch",
    "TreeInspection",
    "TreeNode",
    "export_json",
    "export_text",
    "load",
    "train",
    "train_dense",
]
